
# theme config
theme = "apollo"

base_url = "https://jack-d-long.github.io/"
title = "jdl298"
description = "This is an example description"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/alien.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled





# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false


# Put all your custom variables here

socials = [
  {name = "linkedin", url = "linkedin.com/in/jacklong257", icon = "linkedin" },
  {name = "github", url = "https://github.com/jaacklong/", icon = "github"}
]
menu = [
  { name = "/fast robots", url = "/fast-robots", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 }
    
]

mathjax = true
mathjax_dollar_inline_enable = true

