
# theme config

base_url = "https://jack-d-long.github.io/"
title = "Jack Long"
description = "This is an example description"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/alien.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled




# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false


# Put all your custom variables here

socials = [
  {name = "linkedin", url = "https://linkedin.com/in/jacklong257", icon = "linkedin" },
  {name = "github", url = "https://github.com/jack-d-long/", icon = "github"}
]
menu = [
      { name = "/portfolio", url = "/portfolio", weight = 1 },
    { name = "/about", url = "/about", weight = 4 }

    
]

mathjax = true
mathjax_dollar_inline_enable = true
